### ISSUE TITLE
Yay!

### ISSUE THREAD

**Issue by dgant** [hcpsilva/scipio-bot#1]
(Since GitHub has no other messaging feature)

Cool to see you guys are writing a BW AI in Scala. Feel free to take any parts you need from https://github.com/dgant/purplewave . In particular you may find my Scala-friendly wrapper around BWMirror helpful: https://github.com/dgant/PurpleWave/tree/master/src/ProxyBwapi

**Comment by catarinacps** [comment]
Hi Dan,

The bot we are developing is a uni project, and we will make 2 versions of the bot, one functional and the other object oriented.
Your bot was one of the first resources we found, we will definitely study it and the wrapper thoroughly!
Thanks for your support!! :)
